<?php include 'includes/header.php'; ?>

<main>
  <section class="py-5">
    <div class="site-container container">
      <div class="row">
        <!-- Posts column -->
        <div class="col-12 col-lg-8">
          <div class="card p-4 mb-4">
            <?php
            $category = '1';
            if (isset($_POST['category'])) {
              $category = $_POST['category'];
            }

            // query the database for all categories
            /*
             * Note from @Dave : seems useless to sanitize because POST request
             * */
            $query_category = $mysqli->query("SELECT * FROM categories where id=$category limit 1;");
            // Check for errors
            if (!$query_category) {
              echo "Failed to retrieve categories: " . $mysqli->error;
              exit();
            }

            /* From now on, $category is an object */
            $category = $query_category->fetch_object();
            ?>

            <h2>All posts from <?php
            // if category is null, show "Unknown"
            if ($category->name == null) {
              echo "Unknown";
            } else {
              echo $category->name;
            }

            ?></h2>

            <!-- Search form -->
            <form method="get" action="blog.php" class="mb-3">
              <input type="hidden" name="category" value="<?php echo $category->id; ?>" />
              <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Rechercher..."
                  value="<?php echo isset($_GET['q']) ? htmlspecialchars($_GET['q']) : ''; ?>" />
                <button class="btn btn-primary" type="submit">Rechercher un article</button>
              </div>
            </form>

            <?php

            // Handle optional search query (GET parameter 'q')
            $q = '';
            $search_sql = '';
            if (isset($_GET['q']) && trim($_GET['q']) !== '') {
              $q = $_GET['q'];

              // security : prevent xss to reject if contains <script> or onerror attributes
              if (preg_match('/<script\b[^>]*>(.*?)<\/script>/is', $q) || preg_match('/(.*?)onerror(.*?)/i', $q)) {
                echo '<p class="text-danger">Please, dont try to hack my website</p>';
                $q = '';
              } else {
                // Escape for use in LIKE
                // $escaped_q = $mysqli->real_escape_string($q);
                $escaped_q = $q;
                $search_sql = " AND blog_posts.title LIKE '%" . $escaped_q . "%' ";

                // search in title AND description
                // $search_sql = " AND (blog_posts.title LIKE '%" . $escaped_q . "%' OR blog_posts.content LIKE '%" . $escaped_q . "%')";
              }
            }

            // Show the search result indicator under the form
            echo '<div><p>Résultat de votre recherche : ' . $q . '</p></div>';

            try {
              // Query the database for the latest blog article (filtered by category and optional search)
              // escape category->id to avoid sqli
              $escaped_category_id = $mysqli->real_escape_string($category->id);
              $sql = "SELECT * FROM blog_posts,categories WHERE categories.id=blog_posts.category_id AND categories.id=" . $escaped_category_id . "" . $search_sql . " ORDER BY created_at DESC;";
              $result = $mysqli->query($sql);
            } catch (Exception $e) {
              echo "Failed to retrieve latest blog article: " . $mysqli->error;
              exit();
            }

            // Check for errors
            if (!$result) {
              echo "Failed to retrieve latest blog article: " . $mysqli->error;
              exit();
            }
            ?>
          </div> <!-- .card -->

          <!-- Posts list (generated by PHP loop) -->
          <div class="posts-list mt-4">
            <?php
            // Output the blog articles by category
            while ($article = $result->fetch_assoc()) {
              echo '<div class="row">';
              echo '<div class="col">';
              echo "<h3>" . $article['title'] . "</h3>";
              echo "<div>" . $article['content'] . "</div>";
              echo '</div>';
              echo '</div>';
              echo '<br/>';
            }
            ?>
          </div>
        </div> <!-- .col posts -->

        <!-- Sidebar -->
        <div class="col-12 col-lg-4">
          <aside class="card p-4">
            <h4>A picture of a cat?</h4>
            <?php if (isset($_GET['cat'])) {
              $cat = "/" . $_GET['cat'] . "/" . $_GET['cat'];
            } else {
              $cat = "/200/300";
            }
            ?>
            <p class="text-muted">Yes, a picture of a cat.</p>
            <img src=<?php echo "https://placecats.com" . $cat; ?> alt="A random cat" class="img-fluid rounded mb-3" />
            <a href=<?php echo "/blog.php?cat=" . rand(100, 300); ?> class="btn btn-primary w-100">New random cat</a>
          </aside>
        </div>
      </div> <!-- .row -->
    </div> <!-- .site-container -->
  </section>

</main>
<?php include 'includes/footer.php'; ?>